"""Initial migration for PostgreSQL

Revision ID: d9276dc5649e
Revises: 
Create Date: 2026-02-20 23:40:31.608416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9276dc5649e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Enum('JUNIOR', 'SENIOR', 'MANAGER', 'DIRECTOR', 'EXECUTIVE', name='position_level_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_position_code', 'positions', ['code'], unique=False)
    op.create_index('idx_position_level', 'positions', ['level'], unique=False)
    op.create_index('idx_position_title', 'positions', ['title'], unique=False)
    op.create_index(op.f('ix_positions_code'), 'positions', ['code'], unique=True)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_level'), 'positions', ['level'], unique=False)
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_employee_code', 'employees', ['employee_code'], unique=False)
    op.create_index('idx_employee_department', 'employees', ['department_id'], unique=False)
    op.create_index('idx_employee_email', 'employees', ['email'], unique=False)
    op.create_index('idx_employee_full_name', 'employees', ['full_name'], unique=False)
    op.create_index('idx_employee_position', 'employees', ['position_id'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    op.create_index(op.f('ix_employees_position_id'), 'employees', ['position_id'], unique=False)
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'EARLY_LEAVE', name='attendance_status'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_date')
    )
    op.create_index('idx_attendance_date', 'attendances', ['date'], unique=False)
    op.create_index('idx_attendance_date_status', 'attendances', ['date', 'status'], unique=False)
    op.create_index('idx_attendance_employee', 'attendances', ['employee_id'], unique=False)
    op.create_index('idx_attendance_employee_date', 'attendances', ['employee_id', 'date'], unique=False)
    op.create_index('idx_attendance_employee_status', 'attendances', ['employee_id', 'status'], unique=False)
    op.create_index('idx_attendance_status', 'attendances', ['status'], unique=False)
    op.create_index(op.f('ix_attendances_date'), 'attendances', ['date'], unique=False)
    op.create_index(op.f('ix_attendances_employee_id'), 'attendances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('base_salary', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_salary > 0', name='check_salary_positive'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='check_salary_dates'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_salary_effective_from', 'salaries', ['effective_from'], unique=False)
    op.create_index('idx_salary_effective_to', 'salaries', ['effective_to'], unique=False)
    op.create_index('idx_salary_employee', 'salaries', ['employee_id'], unique=False)
    op.create_index('idx_salary_employee_date', 'salaries', ['employee_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index(op.f('ix_salaries_effective_from'), 'salaries', ['effective_from'], unique=False)
    op.create_index(op.f('ix_salaries_effective_to'), 'salaries', ['effective_to'], unique=False)
    op.create_index(op.f('ix_salaries_employee_id'), 'salaries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_salaries_id'), 'salaries', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'EMPLOYEE', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_user_employee', 'users', ['employee_id'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.Enum('ANNUAL', 'SICK', 'UNPAID', 'MATERNITY', 'PATERNITY', 'EMERGENCY', 'OTHER', name='leave_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='leave_status'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='check_leave_dates'),
    sa.CheckConstraint('total_days > 0', name='check_positive_days'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leave_approved_by', 'leaves', ['approved_by'], unique=False)
    op.create_index('idx_leave_date_range', 'leaves', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_leave_employee', 'leaves', ['employee_id'], unique=False)
    op.create_index('idx_leave_employee_status', 'leaves', ['employee_id', 'status'], unique=False)
    op.create_index('idx_leave_end_date', 'leaves', ['end_date'], unique=False)
    op.create_index('idx_leave_start_date', 'leaves', ['start_date'], unique=False)
    op.create_index('idx_leave_status', 'leaves', ['status'], unique=False)
    op.create_index('idx_leave_type', 'leaves', ['leave_type'], unique=False)
    op.create_index('idx_leave_type_status', 'leaves', ['leave_type', 'status'], unique=False)
    op.create_index(op.f('ix_leaves_approved_by'), 'leaves', ['approved_by'], unique=False)
    op.create_index(op.f('ix_leaves_employee_id'), 'leaves', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leaves_end_date'), 'leaves', ['end_date'], unique=False)
    op.create_index(op.f('ix_leaves_id'), 'leaves', ['id'], unique=False)
    op.create_index(op.f('ix_leaves_leave_type'), 'leaves', ['leave_type'], unique=False)
    op.create_index(op.f('ix_leaves_start_date'), 'leaves', ['start_date'], unique=False)
    op.create_index(op.f('ix_leaves_status'), 'leaves', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaves_status'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_start_date'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_leave_type'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_end_date'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_employee_id'), table_name='leaves')
    op.drop_index(op.f('ix_leaves_approved_by'), table_name='leaves')
    op.drop_index('idx_leave_type_status', table_name='leaves')
    op.drop_index('idx_leave_type', table_name='leaves')
    op.drop_index('idx_leave_status', table_name='leaves')
    op.drop_index('idx_leave_start_date', table_name='leaves')
    op.drop_index('idx_leave_end_date', table_name='leaves')
    op.drop_index('idx_leave_employee_status', table_name='leaves')
    op.drop_index('idx_leave_employee', table_name='leaves')
    op.drop_index('idx_leave_date_range', table_name='leaves')
    op.drop_index('idx_leave_approved_by', table_name='leaves')
    op.drop_table('leaves')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_role_active', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_employee', table_name='users')
    op.drop_index('idx_user_active', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_salaries_id'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_employee_id'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_effective_to'), table_name='salaries')
    op.drop_index(op.f('ix_salaries_effective_from'), table_name='salaries')
    op.drop_index('idx_salary_employee_date', table_name='salaries')
    op.drop_index('idx_salary_employee', table_name='salaries')
    op.drop_index('idx_salary_effective_to', table_name='salaries')
    op.drop_index('idx_salary_effective_from', table_name='salaries')
    op.drop_table('salaries')
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_employee_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_date'), table_name='attendances')
    op.drop_index('idx_attendance_status', table_name='attendances')
    op.drop_index('idx_attendance_employee_status', table_name='attendances')
    op.drop_index('idx_attendance_employee_date', table_name='attendances')
    op.drop_index('idx_attendance_employee', table_name='attendances')
    op.drop_index('idx_attendance_date_status', table_name='attendances')
    op.drop_index('idx_attendance_date', table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_employees_position_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index('idx_employee_position', table_name='employees')
    op.drop_index('idx_employee_full_name', table_name='employees')
    op.drop_index('idx_employee_email', table_name='employees')
    op.drop_index('idx_employee_department', table_name='employees')
    op.drop_index('idx_employee_code', table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_positions_title'), table_name='positions')
    op.drop_index(op.f('ix_positions_level'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_code'), table_name='positions')
    op.drop_index('idx_position_title', table_name='positions')
    op.drop_index('idx_position_level', table_name='positions')
    op.drop_index('idx_position_code', table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
